import type { SupportedLocale } from "@/lib/locales";

// Category slugs and English labels are persisted data. Keep those stable and
// translate only at the display boundary so links, filters, and saved listings
// continue to use the same canonical values.
const koreanLabels: Record<string, string> = {
  "Mobile Phones & Tablets": "휴대폰 & 태블릿",
  "Mobile Phones": "휴대폰",
  Tablets: "태블릿",
  Smartwatches: "스마트워치",
  "Phone Cases": "휴대폰 케이스",
  "Chargers & Cables": "충전기 & 케이블",
  "Power Banks": "보조배터리",
  "Earphones & Headsets": "이어폰 & 헤드셋",
  "Tablet Accessories": "태블릿 액세서리",
  "Computers & Laptops": "컴퓨터 & 노트북",
  Laptops: "노트북",
  "Desktop Computers": "데스크톱 컴퓨터",
  Monitors: "모니터",
  "Computer Components": "컴퓨터 부품",
  Keyboards: "키보드",
  "Mice & Mouse Pads": "마우스 & 마우스패드",
  "Printers & Scanners": "프린터 & 스캐너",
  "Networking Equipment": "네트워크 장비",
  "Storage Devices": "저장 장치",
  "Electronics & Appliances": "전자제품 & 가전",
  Televisions: "TV",
  "Audio Equipment": "오디오 장비",
  Cameras: "카메라",
  "Camera Lenses & Accessories": "카메라 렌즈 & 액세서리",
  Drones: "드론",
  "Refrigerators & Freezers": "냉장고 & 냉동고",
  "Washing Machines & Dryers": "세탁기 & 건조기",
  "Small Kitchen Appliances": "소형 주방가전",
  "Coffee Machines": "커피 머신",
  "Heating & Cooling": "난방 & 냉방",
  "Furniture & Home Decor": "가구 & 인테리어",
  "Sofas & Lounge Suites": "소파 & 거실 가구",
  "Beds & Bed Frames": "침대 & 침대 프레임",
  Mattresses: "매트리스",
  "Dining Tables & Chairs": "식탁 & 의자",
  "Desks & Office Furniture": "책상 & 사무용 가구",
  "Wardrobes & Drawers": "옷장 & 서랍장",
  Lighting: "조명",
  "Rugs, Curtains & Blinds": "러그, 커튼 & 블라인드",
  "Wall Art & Decorations": "벽 장식 & 인테리어 소품",
  "Home & Kitchen": "생활 & 주방",
  Cookware: "조리도구",
  Bakeware: "베이킹 용품",
  "Tableware & Cutlery": "식기 & 커트러리",
  "Kitchen Utensils": "주방 도구",
  "Food Storage & Drinkware": "보관용기 & 음료 용품",
  Bedding: "침구",
  "Towels & Bathroom": "수건 & 욕실용품",
  "Storage & Organisation": "수납 & 정리",
  "Clothing & Fashion": "의류 & 패션",
  "Women's Clothing": "여성 의류",
  "Men's Clothing": "남성 의류",
  "Children's Clothing": "아동 의류",
  Shoes: "신발",
  "Bags & Handbags": "가방 & 핸드백",
  Jewellery: "주얼리",
  Watches: "시계",
  "Sportswear & Workwear": "운동복 & 작업복",
  "Baby & Kids": "유아 & 아동",
  "Prams & Strollers": "유모차",
  "Car Seats & Capsules": "카시트 & 신생아 카시트",
  "Cots & Bassinets": "유아 침대 & 요람",
  "High Chairs & Feeding": "유아 식탁의자 & 수유용품",
  "Baby Clothing": "아기 옷",
  "Baby Safety & Monitors": "유아 안전용품 & 모니터",
  "Educational Toys": "교육용 장난감",
  "Kids' Bikes & Scooters": "어린이 자전거 & 킥보드",
  "Books, Music & Media": "도서 · 음반 · 미디어",
  "Fiction & Non-fiction Books": "소설 & 교양 도서",
  "Children's Books & Textbooks": "어린이 책 & 교재",
  "Language, Art & Cookbooks": "어학, 미술 & 요리책",
  "Comics & Manga": "만화책 & 망가",
  "Vinyl Records & CDs": "바이닐 레코드 & CD",
  "DVDs & Blu-rays": "DVD & 블루레이",
  "Stationery & Journals": "문구 & 다이어리",
  "Hobbies & Collectables": "취미 & 수집품",
  Antiques: "앤틱",
  "Coins, Banknotes & Stamps": "동전, 지폐 & 우표",
  "Trading Cards": "트레이딩 카드",
  "Collectable Figures & Models": "피규어 & 모형",
  "Art & Craft Supplies": "미술 & 공예 용품",
  "Sewing & Knitting": "재봉 & 뜨개질",
  "RC Models & Science Kits": "RC 모형 & 과학 키트",
  "Games & Toys": "게임 & 장난감",
  "Gaming Consoles": "게임 콘솔",
  "Video Games": "비디오 게임",
  "Console Accessories": "콘솔 액세서리",
  "Board Games & Puzzles": "보드게임 & 퍼즐",
  "LEGO & Building Toys": "레고 & 조립 장난감",
  "Dolls, Figures & Soft Toys": "인형, 피규어 & 봉제 장난감",
  "Toy Vehicles & Ride-ons": "장난감 차량 & 승용 완구",
  "Sports & Leisure": "스포츠 & 레저",
  "Fitness & Cardio Equipment": "운동 & 유산소 장비",
  "Bicycles & Accessories": "자전거 & 액세서리",
  "Camping & Hiking": "캠핑 & 하이킹",
  Fishing: "낚시",
  "Water Sports & Swimming": "수상 스포츠 & 수영",
  "Golf & Racquet Sports": "골프 & 라켓 스포츠",
  "Team Sports": "팀 스포츠",
  "Musical Instruments": "악기",
  "Guitars & Amplifiers": "기타 & 앰프",
  "Pianos & Keyboards": "피아노 & 키보드",
  "Drums & Percussion": "드럼 & 타악기",
  "String, Brass & Woodwind": "현악기, 금관악기 & 목관악기",
  "DJ & PA Equipment": "DJ & PA 장비",
  "Microphones & Recording": "마이크 & 녹음 장비",
  "Garden, Tools & DIY": "정원 · 공구 · DIY",
  "Power Tools": "전동 공구",
  "Hand Tools & Tool Storage": "수공구 & 공구 보관",
  "Lawn & Garden Tools": "잔디 & 정원 공구",
  "Plants & Planters": "식물 & 화분",
  "BBQs & Outdoor Cooking": "바비큐 & 야외 조리",
  "Building Materials & DIY": "건축 자재 & DIY",
  "Pet Supplies": "반려동물 용품",
  "Dog Supplies": "강아지 용품",
  "Cat Supplies": "고양이 용품",
  "Food, Bowls & Feeders": "사료, 식기 & 급식기",
  "Crates, Carriers & Bedding": "케이지, 이동장 & 침구",
  "Grooming & Training": "미용 & 훈련용품",
  "Aquarium, Bird & Small Animal": "어항, 조류 & 소동물",
  "Health & Beauty": "건강 & 뷰티",
  Skincare: "스킨케어",
  "Make-up": "메이크업",
  "Haircare & Styling Tools": "헤어케어 & 스타일링 도구",
  "Perfume & Fragrance": "향수 & 프래그런스",
  "Personal Care Devices": "개인 관리 기기",
  "Mobility & Daily Living Aids": "이동 & 일상생활 보조용품",
};

export function getMarketCategoryLabel(label: string, locale: SupportedLocale) {
  if (locale !== "ko") return label;
  const otherCategory = label.match(/^Other (.+)$/);
  if (otherCategory) return `기타 ${koreanLabels[otherCategory[1]] ?? otherCategory[1]}`;
  return koreanLabels[label] ?? label;
}
