"use client";

import Image from "next/image";
import Link from "next/link";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ListingComments } from "@/components/market/ListingComments";
import { ListingSafetyActions } from "@/components/market/ListingSafetyActions";
import { Avatar } from "@/components/ui/Avatar";
import { DialogOverlay, PopupBackdrop } from "@/components/ui/DialogOverlay";
import { TextSizeSection } from "@/components/ui/TextSizeSection";
import type { CommunityPostType } from "@/data/community-posts";

export type CommunityPostDetail = { id: string; type: CommunityPostType; title: string; body: string; location: string; createdAt: string; authorName: string; authorAvatarUrl: string | null; isOwner: boolean; images: { src: string; alt: string }[] };

export function CommunityPostDetailClient({ post }: { post: CommunityPostDetail }) {
  const router = useRouter();
  const [activeImage, setActiveImage] = useState(0);
  const [isGalleryOpen, setIsGalleryOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState<string | null>(null);
  const swipeStartX = useRef<number | null>(null);
  const image = post.images[activeImage];
  const showImage = (index: number) => setActiveImage((index + post.images.length) % post.images.length);
  const deletePost = async () => { if (isDeleting) return; setIsDeleting(true); setDeleteError(null); try { const response = await fetch(`/api/community/posts/${post.id}`, { method: "DELETE" }); const payload = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) throw new Error(payload?.error || "Unable to delete this post."); router.push("/community"); router.refresh(); } catch (error) { setDeleteError(error instanceof Error ? error.message : "Unable to delete this post."); setIsDeleting(false); } };

  return <main className="listing-detail-page community-detail-page">
    <div className="listing-detail-back-row"><Link className="listing-detail-back" href="/community"><i className="fa-solid fa-arrow-left" aria-hidden="true" /> Back to community</Link></div>
    <div className={`listing-detail-layout ${image ? "" : "community-detail-layout-no-image"}`}>
      {image ? <section className="listing-detail-gallery community-detail-gallery" aria-label={`${post.title} images`}><div className="listing-detail-main-image" role="button" tabIndex={0} aria-label={`Open photo ${activeImage + 1} of ${post.images.length} in gallery`} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setIsGalleryOpen(true); } }} onPointerDown={(event) => { swipeStartX.current = event.clientX; }} onPointerUp={(event) => { const distance = swipeStartX.current === null ? 0 : event.clientX - swipeStartX.current; swipeStartX.current = null; if (Math.abs(distance) < 12) setIsGalleryOpen(true); else if (Math.abs(distance) >= 42 && post.images.length > 1) showImage(activeImage + (distance < 0 ? 1 : -1)); }} onPointerCancel={() => { swipeStartX.current = null; }}><Image className="listing-detail-main-backdrop" src={image.src} alt="" fill aria-hidden="true" sizes="(max-width: 900px) 100vw, 68vw" /><Image key={image.src} className="listing-detail-main-photo is-entering-from-next" src={image.src} alt={image.alt} fill priority sizes="(max-width: 900px) 100vw, 68vw" />{post.images.length > 1 ? <><button className="listing-detail-gallery-arrow is-previous" type="button" aria-label="Previous image" onClick={(event) => { event.stopPropagation(); showImage(activeImage - 1); }}><i className="fa-solid fa-chevron-left" aria-hidden="true" /></button><button className="listing-detail-gallery-arrow is-next" type="button" aria-label="Next image" onClick={(event) => { event.stopPropagation(); showImage(activeImage + 1); }}><i className="fa-solid fa-chevron-right" aria-hidden="true" /></button></> : null}<span className="listing-detail-image-count"><i className="fa-regular fa-images" aria-hidden="true" /> {activeImage + 1} / {post.images.length}</span></div>{post.images.length > 1 ? <div className="listing-detail-thumbnails" aria-label="Choose photo">{post.images.map((photo, index) => <button className={index === activeImage ? "is-active" : ""} type="button" key={photo.src} onClick={() => showImage(index)} aria-label={`Show photo ${index + 1}`} aria-pressed={index === activeImage}><Image src={photo.src} alt="" fill sizes="96px" /></button>)}</div> : null}</section> : null}
      <aside className="listing-detail-summary"><div className="listing-detail-heading"><div><div className="listing-detail-status-row"><span className="listing-status status-available">Community</span><span>{post.createdAt}</span></div><h1>{post.title}</h1></div>{post.isOwner ? <button className="listing-detail-save listing-detail-delete" type="button" aria-label="Delete post" onClick={() => setIsDeleteDialogOpen(true)}><i className="fa-solid fa-trash-can" aria-hidden="true" /></button> : null}</div><p className="listing-detail-location"><i className="fa-solid fa-location-dot" aria-hidden="true" /> {post.location}</p><div className="listing-detail-actions"><Link className="listing-detail-message" href="#community-comments-title"><i className="fa-regular fa-comment" aria-hidden="true" /> Join discussion</Link><Link className="listing-detail-offer" href="/community"><i className="fa-solid fa-list" aria-hidden="true" /> More community posts</Link></div><dl className="listing-detail-facts"><div><dt>Post type</dt><dd>{post.type}</dd></div><div><dt>Published</dt><dd>{post.createdAt}</dd></div></dl><section className="listing-detail-seller-card"><div className="listing-detail-seller"><span className="listing-detail-seller-avatar-wrap is-offline"><Avatar src={post.authorAvatarUrl} name={post.authorName} className="listing-detail-seller-avatar" /></span><div><strong>{post.authorName}</strong><span>Community member</span></div></div>{!post.isOwner ? <ListingSafetyActions listingId={post.id} sellerId={null} space="community" /> : null}</section></aside>
    </div>
    {isGalleryOpen && image ? <PopupBackdrop className="listing-gallery-lightbox" role="dialog" aria-modal="true" aria-label={`${post.title} photo gallery`} onClose={() => setIsGalleryOpen(false)}><Image className="listing-gallery-lightbox-backdrop" src={image.src} alt="" fill aria-hidden="true" sizes="100vw" onClick={() => setIsGalleryOpen(false)} /><button className="listing-gallery-lightbox-close" type="button" aria-label="Close photo gallery" onClick={() => setIsGalleryOpen(false)}><i className="fa-solid fa-xmark" aria-hidden="true" /></button><div className="listing-gallery-lightbox-stage"><Image className="listing-gallery-lightbox-photo" src={image.src} alt={image.alt} fill priority sizes="100vw" /></div>{post.images.length > 1 ? <><button className="listing-gallery-lightbox-arrow is-previous" type="button" aria-label="Previous photo" onClick={() => showImage(activeImage - 1)}><i className="fa-solid fa-chevron-left" aria-hidden="true" /></button><button className="listing-gallery-lightbox-arrow is-next" type="button" aria-label="Next photo" onClick={() => showImage(activeImage + 1)}><i className="fa-solid fa-chevron-right" aria-hidden="true" /></button></> : null}<span className="listing-gallery-lightbox-count">{activeImage + 1} / {post.images.length}</span></PopupBackdrop> : null}
    <TextSizeSection className="listing-detail-description" title="Description"><div className="community-detail-body" dangerouslySetInnerHTML={{ __html: post.body }} /></TextSizeSection>
    <section className="listing-detail-mobile-seller listing-detail-mobile-only"><div className="listing-detail-mobile-seller-profile"><span className="listing-detail-mobile-seller-avatar-wrap is-offline"><Avatar src={post.authorAvatarUrl} name={post.authorName} className="listing-detail-mobile-seller-avatar" /></span><div><strong>{post.authorName}</strong><span>Community member</span><small>Posted {post.createdAt}</small></div>{!post.isOwner ? <div className="listing-detail-mobile-seller-actions"><ListingSafetyActions listingId={post.id} sellerId={null} sellerProfileVariant iconOnly space="community" /></div> : null}</div></section>
    <ListingComments listingId={post.id} space="community" />
    {isDeleteDialogOpen ? <DialogOverlay className="listing-delete-backdrop" aria-labelledby="community-delete-title" onClose={() => setIsDeleteDialogOpen(false)} isDismissible={!isDeleting}><section className="listing-delete-dialog"><div className="listing-delete-dialog-icon"><i className="fa-solid fa-trash-can" aria-hidden="true" /></div><h2 id="community-delete-title">Delete this post?</h2><p>This cannot be undone. The post, its images, and comments will be permanently removed.</p>{deleteError ? <p className="listing-delete-error" role="alert">{deleteError}</p> : null}<div><button type="button" onClick={() => setIsDeleteDialogOpen(false)} disabled={isDeleting}>Cancel</button><button className="listing-delete-confirm" type="button" onClick={() => void deletePost()} disabled={isDeleting}>{isDeleting ? "Deleting..." : "Delete post"}</button></div></section></DialogOverlay> : null}
  </main>;
}
